version: '1.0'
services:
  db:
    container_name: urlShortener_db
    image: 'mysql:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: UrlShortener
      MYSQL_USER: admin
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
    ports:
      - '${DATABASE_PORT}:3306'
    volumes:
      - './.urlShortener-db:/var/lib/mysql'
  phpmyadmin:
    container_name: visualizeUrlShortener-db
    image: 'phpmyadmin/phpmyadmin:latest'
    restart: always
    depends_on:
      - db
    ports:
      - '${PHPMYADMIN_PORT}:80'
  webserver:
    container_name: "urlShortener"
    build: .
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ../src/main/:/var/www/html
